
name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Instalar dependencias
      run: 
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt
    - name: Executando testes robot
      run:
        robot -d ./MeusResultados tests
