name: Run Robot Framework Testes

on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt

    build:
      commands:
       - robot -d ./reportFolder -x report.xml tests/
       - zip -r reportFolder/reportFolder.zip reportFolder/

