name: Run Robot Framework Testes

on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        python.version:
          - 3.8

    steps:
    commands:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
    build:
      commands:
       - robot -d ./meusResultados -x report.xml tests/
       - zip -r meusResultados/meusResultados.zip meusResultados/

artifacts:
  base-directory: MeusResultados
  files:
    - 'report.xml'
    - 'meusResultados.zip'
