name: Run Robot Framework Testes

on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  test:
    - name: Run Tests
    runs-on: ubuntu-latest
    
    - name: Set up Python
      uses: actions/setup-python@v2
        - 3.8 

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executando testes robot
      run:
        robot -d ./MeusResultados tests
